test

diff --git a/.github/actions/setup-composite-action/action.yml b/.github/actions/setup-composite-action/action.yml
--- a/.github/actions/setup-composite-action/action.yml
+++ b/.github/actions/setup-composite-action/action.yml
@@ -3,32 +3,33 @@ description: 'Setup Node.js and pnpm'
 runs:
   using: "composite"
   steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        
-      - name: Read .nvmrc file
-        shell: bash
-        id: nvmrc
-        run: |
-          if [ -f .nvmrc ]; then
-            echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
-          else
-            echo "::error::File .nvmrc not found!"
-            exit 1
-          fi
+    - name: Checkout repository
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
-      - name: Set up Node.js
-        shell: bash
-        uses: actions/setup-node@v3
-        with:
-          node-version: ${{ env.NODE_VERSION }}
+    - name: Read .nvmrc file
+      id: nvmrc
+      shell: bash
+      run: |
+        if [ -f .nvmrc ]; then
+          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
+          echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
+        else
+          echo "::error::File .nvmrc not found!"
+          exit 1
+        fi
 
-      - name: Setup pnpm
-        shell: bash
-        uses: pnpm/action-setup@v2
-        with:
-          version: 8
+    - name: Set up Node.js
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ env.NODE_VERSION }}
+        cache: "pnpm"
 
-      - name: Install dependencies
-        shell: bash
-        run: pnpm install
+    - name: Setup pnpm
+      shell: bash
+      run: pnpm install -g pnpm
+
+    - name: Install dependencies
+      shell: bash
+      run: pnpm install
